apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: hello-world
          image: YOUR_DOCKERHUB_USERNAME/hello-world:latest
          imagePullPolicy: Always
      restartPolicy: Never
